baseURL = 'https://ucsb-seclab.github.io/xplor-cvex/'
languageCode = 'en-us'
relativeURLs = true
title = 'Common Vulneravilities and Exposures with Exploits'
theme = 'hugo-xterm'
disableKinds = ["RSS"]
enableInlineShortcodes = true
