baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CVEX'
theme = "hugo-xterm"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/CVEX-2017-1000499/"
    name = "CVEX-2017-1000499"
    weight = 2